--
--  Size of types defined in the Ada part of the kernel that are
--  going to be used by C applications.
--
--  DO NOT EDIT THIS FILE
--
--  This file is automatically generated by mkmarte by calling the
--  script 'mextract_kernel_types_sizes.pl' which extracts the values
--  from 'marte-kernel-types_sizes.o'.

package Kernel_Types_Sizes is

   KERNEL_TCB_SIZE_IN_BYTES : constant := 16#00000190#;
   SCHED_PARAM_SIZE_IN_BYTES : constant := 16#0000001c#;
   PTHREADATTR_SIZE_IN_BYTES : constant := 16#00000088#;
   MUTEX_SIZE_IN_BYTES : constant := 16#0000008c#;
   MUTEXATTR_SIZE_IN_BYTES : constant := 16#00000058#;
   MUTEX_APPSCHED_PARAM_T_SIZE_IN_BYTES : constant := 16#00000040#;
   CV_SIZE_IN_BYTES : constant := 16#000001b8#;
   CVATTR_SIZE_IN_BYTES : constant := 16#00000004#;
   SEM_SIZE_IN_BYTES : constant := 16#000001a8#;
   SIGNAL_SET_SIZE_IN_BYTES : constant := 16#0000003f#;
   STRUCT_SIG_ACTION_SIZE_IN_BYTES : constant := 16#00000048#;
   SIGINFO_T_SIZE_IN_BYTES : constant := 16#0000000c#;
   SIGNAL_EVENT_SIZE_IN_BYTES : constant := 16#0000000c#;
   ITIMERSPEC_SIZE_IN_BYTES : constant := 16#00000010#;
   SCHED_ACTIONS_SET_SIZE_IN_BYTES : constant := 16#0000019c#;
   POSIX_APPSCHED_EVENT_SIZE_IN_BYTES : constant := 16#00000018#;
   POSIX_APPSCHED_EVENTSET_T_SIZE_IN_BYTES : constant := 16#00000004#;
   PTHREAD_KEY_T_SIZE_IN_BYTES : constant := 16#00000004#;
   PTHREAD_ONCE_SIZE_IN_BYTES : constant := 16#00000091#;
   TIMED_HANDLER_TIMED_EVENT_SIZE_IN_BYTES : constant := 16#00000064#;
   TASK_SET_ID_SIZE_IN_BYTES : constant := 16#00000004#;

end Kernel_Types_Sizes;